language: node_js

node_js:
- "node"

sudo: required

cache:
  directories:
    - node_modules

services:
  - postgresql
  - docker

addons:
  postgresql: "9.6"

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - ORIGIN=null
  - IDENTITY_SERVICE_HOST=null
  - AUTH0_CLIENT_ID=null
  - AUTH0_CLIENT_SECRET=null
  - AUTH0_DOMAIN=null
  - AUTH0_LOGIN_CALLBACK_URI=null
  - LOGGLY_TOKEN=null
  - LOGGLY_SUBDOMAIN=null
  - ROLLBAR_SERVER_TOKEN=null
  - ROLLBAR_CLIENT_TOKEN=null
  - GEMFURY_USER=base63
  # GEMFURY_API_KEY=???
  - secure: "Rv26EWnU7VJur64mYEGCL5gGsPbn2EiyxOQtcmmukAGKn5m7h0rKW+luQGDyOX+VctmXtgaB9/d0OhPItSA++8M16OhbPsW0OYYXoXQ1Jkq3QXmJ2PRozZ/f19D+381OFc5te/GcU1JDvCt9VCy1oYis39j5AOkknouMwtcd8ABzE4ayM0oNnge7m4VmINzRvE6iO3ydKxclGZ+qPuyaiUGVpL6GiKLVR7yKXaFBxwPgesXdLmdBR08FGVhh9ojZMKlvFrKj/UgaxML9mDIlimc6SJLydPeMPu0x0850wA2uPt6kbcoVa//Lvn9TVMsLVA8HWLrOgQAszelomXtyihBWpuXDuBgVrlfu4IIChJOHm5ll3SrIAfe2Gvjl6wVekT8gop+63OsEPUkQE8BhZO5M/8WuNEzqxWU/Uza3pU018jqlEC5dxPuSskBPHelY3XNIVWJHPWyGm80lDlXxAex2P3h8BEqRqd2lUXKoCUwUaAGV6Q4IiiE2jEI0qgsrQwY6XIghlHkM7fpIProT3HodEZpuAxWgQTFVxf+U0uO56EKrZr9GzcjU90ZhPSXYntRTu5VQpWeWTd3o/rW9agd29uRn53XS0Ub1gPX+MZ907tHGcrggq/RLCFymL7vOcZzQv5h1apIIV3rB9J7GXIWhEDUwpKiU75Jt+L77y/A="
  - DOCKER_HUB_USERNAME=horia141
  # DOCKER_HUB_PASSWORD
  - secure: "dItxjBItdnELH0Zc4huuaeARylWBGklf1x39qwHYZezKlq9Ihao2UoCDo8IwcQnrTW1iIRz6WzWEToTeJnpHqUXKR9IlDa2RHQljGKCnghC54pw36rO5UDaLi97zGbv4CnXCWv5Gi4wELKw4iAIolMcZTZXbsOWV2IgtyDaaMGjopLQevb40ozqzl3Qav0L+gsCnpDlTwMP9OC24ymhyqas4llGcewy0cSlVQ7gCTZOr+khra8+3APXvxYQ1WZ0hePBZjR5yDBc8AhdTiYEgJtgvU5MGRsTHZybPiQXlUbNJ3AjUh6MyeYZ2gTvtEJn4BBmRkdC2YddTcB7VjXa+2AuUpIyVO+cbxImVVN9rUjna61OYonmCQ7VzYXSTZ7nYasLJMm2C/5nKvhIwxQq5ssAvCp571pAVfl2VpOXLlqg1PW1X4FW1vL61N0f+cTTGZhTut8CdM3nTNJCgZ3K0oNxJ5MjVAVTc2jntGdyCIT83/h+3e5nr2SqWaqEjQhnVKcffK6/zlj6Yxrmut8iw44k/wd4ghtQkfgvuHqDGTkkOU65j69Cklc/sD+XBNWZ7LW0G7Y2KU6xg04DwPiByz/+4fk3Db8KEEK1pNIroI+zRwjMI/ZEC9chCeCN4TGHhIL7HowG/lPA7OD9xHs1dR2XggJWpojttRZPHAstrKpU="

install:
- npm install --registry=https://npm-proxy.fury.io/${GEMFURY_API_KEY}/${GEMFURY_USER}/ --progress=false

before_script:
- psql -c 'create database base63;' -U postgres

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/togemfury --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: docker build --tag base63/base63fe:$TRAVIS_TAG . && docker tag base63/base63fe:$TRAVIS_TAG base63/base63fe:latest && docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" && docker push base63/base63fe:$TRAVIS_TAG && docker push base63/base63fe:latest
  on:
    tags: true
# - provider: heroku
#   skip_cleanup: true
#   app: base63fe-staging-base63
#   api_key:
#     secure: "bkrJktWntQN9CX+C1/u3Hbg81EeJ7siSN6qgYC8l92vCe7KiguxpXa8LyYUmw/rtmCOBrYx51QWzBc2ivaDgrfFepjA4cMDgkTGUwCEJOYwos9Dq1S6AlQPiCsPoI/GtLCPbJf7cntf8iqJiMt4GfqUDEfvagCF5qOiphQtjmCY3wrFcDDB1PgbsBTYq596eEgKr1OcLt8965AL6Krad36WcpMRTTtqVujZdFR3U+VCWCfLd6N6NAWWt8+wUkjMmK2qzv8r1QyUDfmlJbhoh9SrTmP7nIjqhGmo0NTM/j4ANOic+17xhY9I93qTjpmiFO9OZcpa24L/928wMKYB0TH7EppRoODWzOd0PNdYtY3b5BWo2Uxt+HJPH9Mh9GL76A/6mlxNUTzKRo3/uiLloIWQLmEpETjbdMwS2YVpNrsBAEjdS1LO1NkesDXqzyxelODxTNn31tbfGvT/HAPq1/GhDy7gJa3MPdEAMaTMqfOM/Ursejx4sSrJDgsXKG0equJOwTrGY55NGkUUABUDJOM4hMkars/9Q88S+wVWUyV6ruWoKfDy/ljhBSBooT0PLI9nfbsAvV452GTMp/xlkoLcZGtsrHph3TWOQnWT8Q1AEpVVx1fweD8epUCv7wyCJ7uKTq6nJODdZm1mVDkwYIkF4ntpw0uKRONvAB8ePN2M="
#   on:
#     tags: true
